### ISSUE TITLE
No images in PDF

### ISSUE THREAD

**Issue by bertschmid** [DevExpress/dotnet-eud#111]
Add
,"wkhtmltopdf": 
		{
			"additionalArguments" : "--enable-local-file-access"
		}

after "dest": "_pdf"
to docfx.json

on windows file system

please add to documentation

**Comment by natakazakova** [comment]
@bertschmid Thank you for your solution, we've updated the [docfx.json](https://github.com/DevExpress/dotnet-eud/blob/20.2/docfx.json#L74) file.
