### ISSUE TITLE
Hyperlink column doc

### ISSUE THREAD

**Issue by TimThrelkeld** [DevExpress/dotnet-eud#56]
Would it be possible to update the [Dashboard grid columns](https://github.com/DevExpress/dotnet-eud/blob/18.2/dashboard-for-desktop/articles/dashboard-designer/designing-dashboard-items/grid/columns.md/#L1) subject with information about the [new hyperlink column](https://docs.devexpress.com/Dashboard/119458/creating-dashboards/creating-dashboards-in-the-winforms-designer/designing-dashboard-items/grid/columns/hyperlink-column)?

**Comment by natakazakova** [comment]
@TimThrelkeld Thank you for the notice, we've added the info.
https://github.com/DevExpress/dotnet-eud/commit/7eca53eb7fd574ae6fa0d426633d0a5b94346697
